name: Individual branch deployment
on:
  workflow_dispatch:
  push:
    branches: [ "pirani", "rasti", "sadrzade", "sameh", "zahedi" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Create SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" > priv.key
          chmod 600 priv.key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

      - name: Get branch name
        id: get_branch
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Deploy
        run: |
          ssh -i ./priv.key -o StrictHostKeyChecking=no "$SERVER_USERNAME"@"$SERVER_HOST" 'cd /root/dev/Cotopia-Lite-Frontend && git pull origin dev'
          ssh -i ./priv.key -o StrictHostKeyChecking=no "$SERVER_USERNAME"@"$SERVER_HOST" 'cd /root/dev/Cotopia-Lite-Frontend && npm install'
          ssh -i ./priv.key -o StrictHostKeyChecking=no "$SERVER_USERNAME"@"$SERVER_HOST" 'cd /root/dev/Cotopia-Lite-Frontend && npm run build'
          ssh -i ./priv.key -o StrictHostKeyChecking=no "$SERVER_USERNAME"@"$SERVER_HOST" 'cd /root/dev/Cotopia-Lite-Frontend && pm2 restart '${{ env.BRANCH_NAME }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
