# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    # runs-on: ubuntu-latest
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    # - run: jest

  deploy:
    runs-on: self-hosted
    needs:  [ build ]
    steps:

      - name: Create SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" > priv.key
          sudo chmod 600 priv.key
        env:
          SSH_PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
          # SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          # SSH_KEY_PATH: ${{ github.workspace }}/../private.key

      - name: Deploy
        run: |
          ssh -i priv.key -o StrictHostKeyChecking=no "$SERVER_USERNAME"@"SERVER_HOST"
          cd /root/dev/Cotopia-Lite-Frontend
          echo "Deploy" > deploy.txt

      # - name: Deploy
      #   run: |
      #     ssh -i priv.key -o StrictHostKeyChecking=no "$SERVER_USERNAME"@"SERVER_HOST"
      #     cd /root/dev/Cotopia-Lite-Frontend
      #     echo "Deploy" > deploy.txt


      # - name: Deploy
      #   uses: D3rHase/ssh-command-action@latest
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     user: ${{ secrets.SERVER_USERNAME }}
      #     private_key: ${{ secrets.PRIVATE_KEY }}
      #     port: ${{ secrets.SERVER_PORT }}
      #     command: |
      #       cd /root/dev/Cotopia-Lite-Frontend
      #       echo "Deploy" > deploy.txt